### ISSUE TITLE
strong_sort weight file read problem

### ISSUE THREAD

**Issue by jklkid** [mikel-brostrom/Yolov5_StrongSORT_OSNet#482] opened 2022-08-08 05:19 UTC
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

I was unable to download the strong_sort weights file online, so I chose to download the weights manually from the model zoo. However, after the downloaded weight is placed in the corresponding folder, the code cannot be read, and the online download is still performed. Is it due to the weight format being .pth? How to solve it?

**Comment by mikel-brostrom** [comment] 2022-08-08 05:56
ReID weigths are always in `.pt` format unless you change their extension. The file extension does not change anything in the saved file. The recommended extensions are just used in order to make everyone recognize that it actually is a model saved from pytorch. 

I recommend you however to use `.pt` extension because `.pth` is used by Python itself for `site-packages` and module path pointing

**Comment by jklkid** [comment] 2022-08-08 06:11
> ReID weigths are always in `.pt` format unless you change their extension. The file extension does not change anything in the saved file. The recommended extensions are just used in order to make everyone recognize that it actually is a model saved from pytorch.
> 
> I recommend you however to use `.pt` extension because `.pth` is used by Python itself for `site-packages` and module path pointing

Does changing the extension require a format conversion code for a .pth to .pt change? Is it possible to change the extension directly? I've tried changing the .pth extension directly to .pt format, but it doesn't seem to be recognized when running the code. The code will still automatically run the online download program.

**Comment by mikel-brostrom** [comment] 2022-08-08 08:27
> Is it possible to change the extension directly?

Yes. Set the `--strong-sort-weights` accordingly

**Comment by besubtle** [comment] 2022-08-08 09:40
hello,  I had the same problem as you @jklkid , and I also tried some measures to solve this problem. 
maybe you could try solve it like me, and I'll share my method with you.
first, if you can not download the weights file online when running `track.py`,  you could try to create a new `.py` file and use `gdown` to download the weights file online.

```python
import gdown

#find your model_url in path:`Yolov5_StrongSORT_OSNet/strong_sort/deep/reid_model_factory.py`
model_url = "https://drive.google.com/uc?id=1sSwXSUlj4_tHZequ_iZ8w_Jh0VaRQMqF"  
weights = "./osnet_x0_25_msmt17.pt"

gdown.download(model_url, str(weights), quiet=False)
```
run this file to download your weights files, and you'll see the following print:
```
torch171) sunquanlin@sql:~/Documents$ /home/sunquanlin/anaconda3/envs/torch171/bin/python /home/sunquanlin/Documents/download.py
Downloading...
From: https://drive.google.com/uc?id=1sSwXSUlj4_tHZequ_iZ8w_Jh0VaRQMqF
To: /home/sunquanlin/Documents/osnet_x0_25_msmt17.pt   #The suffix of the file name is pt
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.06M/3.06M [00:02<00:00, 1.38MB/s]
```
**NOTE**
if you down the weight file directly visiting `model_url` in your browser, the website will download the `.pth` file for you,

**Comment by jklkid** [comment] 2022-08-09 01:18
> hello, I had the same problem as you @jklkid , and I also tried some measures to solve this problem. maybe you could try solve it like me, and I'll share my method with you. first, if you can not download the weights file online when running `track.py`, you could try to create a new `.py` file and use `gdown` to download the weights file online.
> 
> ```python
> import gdown
> 
> #find your model_url in path:`Yolov5_StrongSORT_OSNet/strong_sort/deep/reid_model_factory.py`
> model_url = "https://drive.google.com/uc?id=1sSwXSUlj4_tHZequ_iZ8w_Jh0VaRQMqF"  
> weights = "./osnet_x0_25_msmt17.pt"  ##The suffix of the file name is pt
> 
> gdown.download(model_url, str(weights), quiet=False)
> ```
> 
> run this file to download your weights files, and you'll see the following print:
> 
> ```
> torch171) sunquanlin@sql:~/Documents$ /home/sunquanlin/anaconda3/envs/torch171/bin/python /home/sunquanlin/Documents/download.py
> Downloading...
> From: https://drive.google.com/uc?id=1sSwXSUlj4_tHZequ_iZ8w_Jh0VaRQMqF
> To: /home/sunquanlin/Documents/osnet_x0_25_msmt17.pt   
> 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.06M/3.06M [00:02<00:00, 1.38MB/s]
> ```
> 
> **NOTE** if you down the weight file directly visiting `model_url` in your browser, the website will download the `.pth` file for you,

Glad you can provide valuable advice on my question. But I tried the method you gave and got an error.
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443)
Could it be a proxy problem? My web proxy is SOCKS, do I need an HTTPS proxy to download? But I can't change the proxy, is there any other solution?

**Comment by besubtle** [comment] 2022-08-09 01:59
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443)

I've had this problem before. It may be a problem caused by your network.
Can you access that `model_url` directly in your browser? You need to make sure your network is accessible to Google Drive

**Comment by jklkid** [comment] 2022-08-09 02:08
> model_url



> SOCKS

Yes, I can download the weights directly by opening the webpage in the browser. So I wonder if it's a proxy type issue? I am using a SOCKS proxy. I looked at the question and someone mentioned using an HTTPS proxy. But I can't change the proxy. I don't know if there is any other way to get the .pt format?

**Comment by jklkid** [comment] 2022-08-09 02:08
> > requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443)
> 
> I've had this problem before. It may be a problem caused by your network. Can you access that `model_url` directly in your browser? You need to make sure your network is accessible to Google Drive

Yes, I can download the weights directly by opening the webpage in the browser. So I wonder if it's a proxy type issue? I am using a SOCKS proxy. I looked at the question and someone mentioned using an HTTPS proxy. But I can't change the proxy. I don't know if there is any other way to get the .pt format?

**Comment by besubtle** [comment] 2022-08-09 02:37
> So I wonder if it's a proxy type issue?

sorry, I have no idea about it.  `.pth` format could be converted to `.pt` format, but I  have not tried that conversion.

**Comment by YuNaruto** [comment] 2022-08-09 07:01
Unable to download due to network problems.
Download directly from the web page, but not in PT format.

**Comment by jklkid** [comment] 2022-08-09 07:26
> Unable to download due to network problems. Download directly from the web page, but not in PT format.

How to convert .pth format to .pt format? Modifying the extension directly seems useless. Need special format conversion code?

**Comment by jklkid** [comment] 2022-08-09 07:32
> > Is it possible to change the extension directly?
> 
> Yes. Set the `--strong-sort-weights` accordingly

What if I want to train strong_sort weights on my own dataset?

**Comment by YuNaruto** [comment] 2022-08-09 07:40
I also want to know how to download `pt` format directly.

**Comment by YuNaruto** [comment] 2022-08-09 08:36
import 
state_dict = torch.load(r"osnet_x0_25_msmt17_256x128_amsgrad_ep180_stp80_lr0.003_b128_fb10_softmax_labelsmooth_flip.pth")
torch.save(state_dict, 'osnet_x0_25_msmt17.pt')

**Comment by jklkid** [comment] 2022-08-09 09:35
> import state_dict = torch.load(r"osnet_x0_25_msmt17_256x128_amsgrad_ep180_stp80_lr0.003_b128_fb10_softmax_labelsmooth_flip.pth") torch.save(state_dict, 'osnet_x0_25_msmt17.pt')

Are you able to run code using this method? I tried your method and successfully converted .pth to .pt. But when running track.py, the downloader will still start automatically.
parser.add_argument('--strong-sort-weights', type=str, default=WEIGHTS / 'D:/project_Yolov5_StrongSORT_OSNet/strong_sort/deep/checkpoint/osnet_x0_25_msmt17.pt')
If you are successful, where is your weights file located? Or should I turn off the automatic downloader?

**Comment by YuNaruto** [comment] 2022-08-09 09:56
> > import state_dict = torch.load(r"osnet_x0_25_msmt17_256x128_amsgrad_ep180_stp80_lr0.003_b128_fb10_softmax_labelsmooth_flip.pth") torch.save(state_dict, 'osnet_x0_25_msmt17.pt')
> 
> Are you able to run code using this method? I tried your method and successfully converted .pth to .pt. But when running track.py, the downloader will still start automatically. parser.add_argument('--strong-sort-weights', type=str, default=WEIGHTS / 'D:/project_Yolov5_StrongSORT_OSNet/strong_sort/deep/checkpoint/osnet_x0_25_msmt17.pt') If you are successful, where is your weights file located? Or should I turn off the automatic downloader?

Yes, I successfully run it. If you succeed in transferring it, it must be that your weight address is incorrect, which will cause the download to continue.

**Comment by jklkid** [comment] 2022-08-10 01:53
> > > import state_dict = torch.load(r"osnet_x0_25_msmt17_256x128_amsgrad_ep180_stp80_lr0.003_b128_fb10_softmax_labelsmooth_flip.pth") torch.save(state_dict, 'osnet_x0_25_msmt17.pt')
> > 
> > 
> > Are you able to run code using this method? I tried your method and successfully converted .pth to .pt. But when running track.py, the downloader will still start automatically. parser.add_argument('--strong-sort-weights', type=str, default=WEIGHTS / 'D:/project_Yolov5_StrongSORT_OSNet/strong_sort/deep/checkpoint/osnet_x0_25_msmt17.pt') If you are successful, where is your weights file located? Or should I turn off the automatic downloader?
> 
> Yes, I successfully run it. If you succeed in transferring it, it must be that your weight address is incorrect, which will cause the download to continue.
After I changed the path the automatic download no longer appeared, but the following error occurred. Have you encountered similar errors? What's going on here?

Traceback (most recent call last):
  File "D:\project_Yolov5_StrongSORT_OSNet\Yolov5_StrongSORT_OSNet-master\track.py", line 323, in <module>
    main(opt)
  File "D:\project_Yolov5_StrongSORT_OSNet\Yolov5_StrongSORT_OSNet-master\track.py", line 318, in main
    run(**vars(opt))
  File "D:\Anaconda3\envs\deepsort\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\project_Yolov5_StrongSORT_OSNet\Yolov5_StrongSORT_OSNet-master\track.py", line 119, in run
    StrongSORT(
  File "D:\project_Yolov5_StrongSORT_OSNet\Yolov5_StrongSORT_OSNet-master\strong_sort\strong_sort.py", line 34, in __init__
    self.model = ReIDDetectMultiBackend(weights=model_weights, device=device, fp16=fp16)
  File "D:\project_Yolov5_StrongSORT_OSNet\Yolov5_StrongSORT_OSNet-master\strong_sort\reid_multibackend.py", line 48, in __init__
    self.extractor = FeatureExtractor(
  File "D:\project_Yolov5_StrongSORT_OSNet\Yolov5_StrongSORT_OSNet-master\strong_sort\torchreid\utils\feature_extractor.py", line 71, in __init__
    model = build_model(
  File "D:\project_Yolov5_StrongSORT_OSNet\Yolov5_StrongSORT_OSNet-master\strong_sort\torchreid\models\__init__.py", line 111, in build_model
    raise KeyError(
KeyError: "Unknown model: None. Must be one of

**Comment by mikel-brostrom** [comment] 2022-08-11 11:21
Btw @YuNaruto, @jklkid, there is no need in doing this:

```python
import torch
state_dict = torch.load(r"osnet_x0_25_msmt17_256x128_amsgrad_ep180_stp80_lr0.003_b128_fb10_softmax_labelsmooth_flip.pth")
torch.save(state_dict, 'osnet_x0_25_msmt17.pt')
```

just rename the file

**Comment by YuNaruto** [comment] 2022-08-11 11:33
> Btw @YuNaruto, @jklkid, there is no need in doing this:
> 
> ```python
> import torch
> state_dict = torch.load(r"osnet_x0_25_msmt17_256x128_amsgrad_ep180_stp80_lr0.003_b128_fb10_softmax_labelsmooth_flip.pth")
> torch.save(state_dict, 'osnet_x0_25_msmt17.pt')
> ```
> 
> just rename the termination for the file from `.pth` to `.pt` and set the path to it accordingly

yes

**Closed** 2022-08-11 11:35 UTC
Labels: question

**Comment by rajivratan-clip** [comment] 2025-09-04 15:30
hey i want to download OsNet Reid weights with this :
`!mkdir -p strong_sort/deep/reid/ckpt
!wget -O strong_sort/deep/reid/ckpt/osnet_x0_25_msmt17.pt \
https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/releases/download/v0.2/osnet_x0_25_msmt17.pt
`
but this is causing me 
`-- https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/releases/download/v0.2/osnet_x0_25_msmt17.pt
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2025-09-04 15:24:51 ERROR 404: Not Found.`
whats the correct process
